#!/bin/bash

Compound="$1"
input_path="$2"
scripts_path="$3"
lam_sim="$4"
epsCH3_sim="$5"
sigCH3_sim="$6"
epsCH2_sim="$7"
sigCH2_sim="$8"
epsCH_sim="$9"
sigCH_sim="${10}"
epsC_sim="${11}"
sigC_sim="${12}"
bondlength_CH3="${13}"
Nmol="${14}"
MCMC_tors="${15}"
iMCMC="${16}"

python "$scripts_path"/create_tab.py --lam "$lam_sim" --epsilon "$epsCH3_sim" --sigma "$sigCH3_sim"

C6_CH3_sim=$(<C6_it)
Clam_CH3_sim=$(<Clam_it)

python "$scripts_path"/create_tab.py --lam "$lam_sim" --epsilon "$epsCH2_sim" --sigma "$sigCH2_sim"

C6_CH2_sim=$(<C6_it)
Clam_CH2_sim=$(<Clam_it)

python "$scripts_path"/create_tab.py --lam "$lam_sim" --epsilon "$epsCH_sim" --sigma "$sigCH_sim"

C6_CH_sim=$(<C6_it)
Clam_CH_sim=$(<Clam_it)

python "$scripts_path"/create_tab.py --lam "$lam_sim" --epsilon "$epsC_sim" --sigma "$sigC_sim"

C6_C_sim=$(<C6_it)
Clam_C_sim=$(<Clam_it)

python "$scripts_path"/comb_rule.py -c geometric -x "$epsCH3_sim" "$epsCH2_sim"

epsCH3CH2_sim=$(<comb_rule)

python "$scripts_path"/comb_rule.py -c geometric -x "$epsCH3_sim" "$epsCH_sim"

epsCH3CH_sim=$(<comb_rule)

python "$scripts_path"/comb_rule.py -c geometric -x "$epsCH3_sim" "$epsC_sim"

epsCH3C_sim=$(<comb_rule)

python "$scripts_path"/comb_rule.py -c geometric -x "$epsCH2_sim" "$epsCH_sim"

epsCH2CH_sim=$(<comb_rule)

python "$scripts_path"/comb_rule.py -c geometric -x "$epsCH2_sim" "$epsC_sim"

epsCH2C_sim=$(<comb_rule)

python "$scripts_path"/comb_rule.py -c geometric -x "$epsCH_sim" "$epsC_sim"

epsCHC_sim=$(<comb_rule)

python "$scripts_path"/comb_rule.py -c arithmetic -x "$sigCH3_sim" "$sigCH2_sim"

sigCH3CH2_sim=$(<comb_rule)

python "$scripts_path"/comb_rule.py -c arithmetic -x "$sigCH3_sim" "$sigCH_sim"

sigCH3CH_sim=$(<comb_rule)

python "$scripts_path"/comb_rule.py -c arithmetic -x "$sigCH3_sim" "$sigC_sim"

sigCH3C_sim=$(<comb_rule)

python "$scripts_path"/comb_rule.py -c arithmetic -x "$sigCH2_sim" "$sigCH_sim"

sigCH2CH_sim=$(<comb_rule)

python "$scripts_path"/comb_rule.py -c arithmetic -x "$sigCH2_sim" "$sigC_sim"

sigCH2C_sim=$(<comb_rule)

python "$scripts_path"/comb_rule.py -c arithmetic -x "$sigCH_sim" "$sigC_sim"

sigCHC_sim=$(<comb_rule)

python "$scripts_path"/create_tab.py --lam "$lam_sim" --epsilon "$epsCH3CH2_sim" --sigma "$sigCH3CH2_sim"

C6_CH3CH2_sim=$(<C6_it)
Clam_CH3CH2_sim=$(<Clam_it)

python "$scripts_path"/create_tab.py --lam "$lam_sim" --epsilon "$epsCH3CH_sim" --sigma "$sigCH3CH_sim"

C6_CH3CH_sim=$(<C6_it)
Clam_CH3CH_sim=$(<Clam_it)

python "$scripts_path"/create_tab.py --lam "$lam_sim" --epsilon "$epsCH3C_sim" --sigma "$sigCH3C_sim"

C6_CH3C_sim=$(<C6_it)
Clam_CH3C_sim=$(<Clam_it)

python "$scripts_path"/create_tab.py --lam "$lam_sim" --epsilon "$epsCH2CH_sim" --sigma "$sigCH2CH_sim"

C6_CH2CH_sim=$(<C6_it)
Clam_CH2CH_sim=$(<Clam_it)

python "$scripts_path"/create_tab.py --lam "$lam_sim" --epsilon "$epsCH2C_sim" --sigma "$sigCH2C_sim"

C6_CH2C_sim=$(<C6_it)
Clam_CH2C_sim=$(<Clam_it)

python "$scripts_path"/create_tab.py --lam "$lam_sim" --epsilon "$epsCHC_sim" --sigma "$sigCHC_sim"

C6_CHC_sim=$(<C6_it)
Clam_CHC_sim=$(<Clam_it)

echo "$epsCH3_sim" "$sigCH3_sim" "$lam_sim" "$epsCH2_sim" "$sigCH2_sim" "$lam_sim" "$epsCH_sim" "$sigCH_sim" "$lam_sim" "$epsC_sim" "$sigC_sim" "$lam_sim" "$epsCH3CH2_sim" "$sigCH3CH2_sim" "$lam_sim" "$epsCH3CH_sim" "$sigCH3CH_sim" "$lam_sim" "$epsCH3C_sim" "$sigCH3C_sim" "$lam_sim" "$epsCH2CH_sim" "$sigCH2CH_sim" "$lam_sim" "$epsCH2C_sim" "$sigCH2C_sim" "$lam_sim" "$epsCHC_sim" "$sigCHC_sim" "$lam_sim" > eps_sig_lam_ref
echo "$bondlength_CH3" > bondlength_CH3

if [ "$MCMC_tors" = "NO" ]
then

cp "$input_path"/"$Compound"_temp.top "$Compound".top 

#CH2_CH2_tors_sim=(8.39736  16.78632   1.13393  -26.31760   0.00000   0.00000)
#CH2_CH_tors_sim=(3.28629   7.44211   1.85995  -14.67569   0.00000   0.00000)
#CH2_C_tors_sim=(3.83538  11.50613   0.00000  -15.34151   0.00000   0.00000)
#CH_CH_tors_sim=(3.28629   7.44211   1.85995  -14.67569   0.00000   0.00000)

elif [ "$MCMC_tors" = "YES" ]
then

cp "$input_path"/"$Compound"_temp_tors.top "$Compound".top 

CH2_CH2_tors_sim=$(awk -v i="$((iMCMC+1))" 'FNR == i {print}' < ~/MCMC_parameter_sets/MCMC_CH2_CH2_tors)
CH2_CH_tors_sim=$(awk -v i="$((iMCMC+1))" 'FNR == i {print}' < ~/MCMC_parameter_sets/MCMC_CH2_CH_tors)
CH2_C_tors_sim=$(awk -v i="$((iMCMC+1))" 'FNR == i {print}' < ~/MCMC_parameter_sets/MCMC_CH2_C_tors)
CH_CH_tors_sim=$(awk -v i="$((iMCMC+1))" 'FNR == i {print}' < ~/MCMC_parameter_sets/MCMC_CH_CH_tors)

sed -i -e s/some_CH2_CH2_tors/"${CH2_CH2_tors_sim[@]}"/ "$Compound".top
sed -i -e s/some_CH2_CH_tors/"${CH2_CH_tors_sim[@]}"/ "$Compound".top
sed -i -e s/some_CH2_C_tors/"${CH2_C_tors_sim[@]}"/ "$Compound".top
sed -i -e s/some_CH_CH_tors/"${CH_CH_tors_sim[@]}"/ "$Compound".top

else

echo "MCMC_tors must be given a value of YES or NO"
exit 0 

fi

cp "$input_path"/"$Compound".gro "$Compound".gro 
sed -i -e s/some_C6_CH3/"$C6_CH3_sim"/ "$Compound".top
sed -i -e s/some_Clam_CH3/"$Clam_CH3_sim"/ "$Compound".top
sed -i -e s/some_C6_CH2/"$C6_CH2_sim"/ "$Compound".top
sed -i -e s/some_Clam_CH2/"$Clam_CH2_sim"/ "$Compound".top
sed -i -e s/some_C6_CH/"$C6_CH_sim"/ "$Compound".top
sed -i -e s/some_Clam_CH/"$Clam_CH_sim"/ "$Compound".top
sed -i -e s/some_C6_C/"$C6_C_sim"/ "$Compound".top
sed -i -e s/some_Clam_C/"$Clam_C_sim"/ "$Compound".top

sed -i -e s/some_C6_combCH3CH2/"$C6_CH3CH2_sim"/ "$Compound".top
sed -i -e s/some_Clam_combCH3CH2/"$Clam_CH3CH2_sim"/ "$Compound".top
sed -i -e s/some_C6_combCH3CH/"$C6_CH3CH_sim"/ "$Compound".top
sed -i -e s/some_Clam_combCH3CH/"$Clam_CH3CH_sim"/ "$Compound".top
sed -i -e s/some_C6_combCH3C/"$C6_CH3C_sim"/ "$Compound".top
sed -i -e s/some_Clam_combCH3C/"$Clam_CH3C_sim"/ "$Compound".top
sed -i -e s/some_C6_combCH2CH/"$C6_CH2CH_sim"/ "$Compound".top
sed -i -e s/some_Clam_combCH2CH/"$Clam_CH2CH_sim"/ "$Compound".top
sed -i -e s/some_C6_combCH2C/"$C6_CH2C_sim"/ "$Compound".top
sed -i -e s/some_Clam_combCH2C/"$Clam_CH2C_sim"/ "$Compound".top
sed -i -e s/some_C6_combCHC/"$C6_CHC_sim"/ "$Compound".top
sed -i -e s/some_Clam_combCHC/"$Clam_CHC_sim"/ "$Compound".top

sed -i -e s/some_bondlength_CH3/"$bondlength_CH3"/g "$Compound".top
sed -i -e s/some_Nmol/"$Nmol"/ "$Compound".top
